# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [1]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [2]:
# Load data here
df = pd.read_csv('data/listings.csv', sep = ',')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [3]:
# 1. How many listings are there with a price less than 100? 

df['new_price'] = df['price'] < 100
df['new_price'].value_counts()

False    23749
True     22778
Name: new_price, dtype: int64

In [4]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.
df['df_bk'] = df['neighbourhood_group'] == 'Brooklyn'
df['df_bk'].value_counts()

# same result
# dfBK['neighbourhood_group' == 'Brooklyn']
# len(dfBK)

False    27895
True     18632
Name: df_bk, dtype: int64

In [1]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.

condition_1 = df['price'] < 100
condition_2 = df['neighbourhood_group'] == 'Brooklyn'

df[condition_1 & condition_2]

NameError: name 'df' is not defined

In [6]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
list_of_host_name = ['Michael', 'David', 'John', 'Daniel']

condition = df.host_name.isin(list_of_host_name)
df[condition]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,new_price,df_bk
52,16595,LOFT HAVEN ~ Six Windows ~ Bricks ~ Plants ~ Q...,64522,Daniel,Brooklyn,Williamsburg,40.70933,-73.96792,Entire home/apt,271,1,172,2020-07-14,1.44,1,365,False,True
201,61747,"Cozy, Brooklyn, Prospect Park Studio",299370,David,Brooklyn,Prospect-Lefferts Gardens,40.65979,-73.96180,Entire home/apt,91,14,97,2018-01-31,0.83,1,44,True,True
209,62903,Beautiful modern studio apartment in heart of NYC,306605,Daniel,Manhattan,Chelsea,40.74238,-73.99567,Entire home/apt,205,15,68,2019-12-14,0.67,2,89,False,False
220,64015,Prime East Village 1 Bedroom,146944,David,Manhattan,East Village,40.72807,-73.98594,Entire home/apt,200,3,0,NaN,NaN,1,0,False,False
260,74073,Food & Music Dream Apartment in Williamsburg,211877,Daniel,Brooklyn,Williamsburg,40.71113,-73.96054,Entire home/apt,187,30,90,2020-07-31,0.81,1,261,False,True
349,138216,Sunny and Spacious Designer's Home,674970,Michael,Brooklyn,Greenpoint,40.72212,-73.94254,Entire home/apt,100,6,9,2019-09-20,0.17,1,0,False,True
351,140133,Truly Amazing Oasis In The City,622866,Daniel,Brooklyn,Williamsburg,40.71363,-73.96019,Entire home/apt,255,3,172,2020-07-02,1.56,1,319,False,True
363,148201,NYC - Sunny Greenwich Village 1br,715807,John,Manhattan,Greenwich Village,40.72831,-74.00177,Entire home/apt,175,3,18,2013-05-31,0.16,1,0,False,False
402,167013,Spacious modern studio apartment in Manhattan,306605,Daniel,Manhattan,Chelsea,40.74342,-73.99483,Entire home/apt,205,10,3,2018-05-13,0.04,2,90,False,False
431,187986,Comfort at Crossroads of Downtown,904833,Daniel,Manhattan,Chelsea,40.73862,-73.99758,Entire home/apt,250,1,2,2015-08-28,0.02,1,0,False,False
434,189135,Hell's Kitchen Funky 80s Hideaway,179020,Michael,Manhattan,Hell's Kitchen,40.76311,-73.99388,Private room,104,1,101,2019-12-28,0.98,1,365,False,False
435,189181,Room in Chic Modern High Line Luxury- New!,912541,David,Manhattan,Chelsea,40.74695,-74.00454,Private room,282,4,1,2014-04-20,0.01,1,0,False,False
479,212544,Quiet One Bedroom in Park Slope,1096084,Daniel,Brooklyn,Gowanus,40.67688,-73.98590,Entire home/apt,100,7,9,2016-06-23,0.08,1,0,False,True
515,233189,NYC Studio in Heart of Times Square,1220414,Michael,Manhattan,Hell's Kitchen,40.76166,-73.99675,Entire home/apt,85,30,89,2020-03-14,0.83,1,153,True,False
520,234870,Private Room With GREAT Location,1229984,John,Queens,Long Island City,40.74581,-73.95295,Private room,75,2,65,2017-07-31,0.64,1,259,True,False
523,235951,Stylish Studio with exclusive Terrace,1236070,Daniel,Manhattan,Midtown,40.75348,-73.97065,Entire home/apt,135,30,143,2020-04-15,1.33,1,260,False,False
585,255637,"Prime Prospect Heights, Brooklyn",1343814,Michael,Brooklyn,Prospect Heights,40.67336,-73.96541,Private room,65,31,40,2020-08-08,0.43,1,0,True,True
589,257787,Heart of Williamsburg. Brand New.,1356046,Daniel,Brooklyn,Williamsburg,40.71408,-73.94890,Entire home/apt,89,18,272,2020-03-23,2.55,2,104,True,True
650,274257,Duplex on the Upper East Side-59th,1434224,Michael,Manhattan,Upper East Side,40.76321,-73.96435,Private room,72,3,16,2019-08-17,0.15,1,273,True,False
691,289037,"2BR in Cobble Hill, Brooklyn, NY",632334,Michael,Brooklyn,Carroll Gardens,40.68353,-73.99140,Entire home/apt,189,2,14,2019-09-08,0.16,1,0,False,True
745,318021,Room in Huge 1200sf W Harlem Suite,1632149,Michael,Manhattan,Harlem,40.80343,-73.95310,Private room,110,3,56,2020-02-03,0.59,1,331,False,False
824,396636,Stylish Designer Studio with Piano,1981742,Daniel,Manhattan,Harlem,40.83091,-73.94223,Entire home/apt,135,5,42,2019-12-10,0.42,1,330,False,False
830,399946,Light Superhosted Chill LES Apt,1996265,David,Manhattan,Lower East Side,40.72123,-73.98996,Entire home/apt,80,10,79,2020-08-01,0.78,1,15,True,False
831,400039,Big Beautiful Railroad in Brooklyn,1488809,John,Brooklyn,Bushwick,40.70339,-73.92945,Entire home/apt,130,30,53,2017-06-30,0.58,1,0,False,True
869,433414,Spacious & Sunny in Prime Brooklyn,287733,David,Brooklyn,Clinton Hill,40.68472,-73.96691,Entire home/apt,99,30,100,2020-07-31,1.01,1,350,True,True
903,456110,Beautiful One Bedroom in Chelsea,2267508,Daniel,Manhattan,Chelsea,40.74760,-73.99698,Entire home/apt,139,4,23,2015-10-04,0.23,1,0,False,False
905,456457,West Village Gem - 2BR,1594083,David,Manhattan,West Village,40.73204,-74.00189,Entire home/apt,315,3,7,2016-08-29,0.07,1,0,False,False
919,467866,"Our NY home, Greenwich Village apt",2321870,David,Manhattan,West Village,40.73123,-74.00591,Private room,100,2,216,2020-02-18,2.16,1,178,False,False
943,484297,Large home in most desirable Brooklyn hood!,2397411,John,Brooklyn,Clinton Hill,40.68545,-73.96534,Entire home/apt,375,4,12,2019-08-17,0.12,1,0,False,True
947,486350,Great 2 bedroom apartment in Williamsburg!,2407024,Michael,Brooklyn,Williamsburg,40.70821,-73.95352,Entire home/apt,225,7,13,2016-08-21,0.13,2,319,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,44081738,Smart & Safe entire home in Staten Island NY,352065598,Daniel,Staten Island,Oakwood,40.56137,-74.10729,Entire home/apt,70,1,1,2020-08-09,1.00,1,256,True,False
45590,44088976,"Spacious oasis - office, private garden, parking",1704370,David,Brooklyn,Clinton Hill,40.68574,-73.96126,Entire home/apt,140,3,1,2020-07-25,1.00,1,17,False,True
45618,44114508,2 huge bedrooms + private toilet & kitchen,352021160,John,Brooklyn,Crown Heights,40.67155,-73.94618,Private room,75,28,0,NaN,NaN,2,364,True,True
45635,44128750,Townhouse Loft By Central Park!,15654886,Michael,Manhattan,Upper West Side,40.79170,-73.96706,Entire home/apt,113,365,0,NaN,NaN,1,359,False,False
45636,44131715,Spotless upper east side full 1 bedroom apartment,118744531,Daniel,Manhattan,Upper East Side,40.76865,-73.95250,Entire home/apt,105,3,2,2020-08-01,2.00,1,43,False,False
45856,44293422,"Entire, Private East Village Apartment, Sleeps 3",2267153,John,Manhattan,East Village,40.72891,-73.98420,Entire home/apt,141,2,0,NaN,NaN,3,47,False,False
45864,44303746,Large 1 bedroom-Flatiron with Elevator/Laundry,89423293,Michael,Manhattan,Chelsea,40.73825,-73.99494,Entire home/apt,125,150,0,NaN,NaN,1,357,False,False
45939,44340349,Private Bedroom at a Great Location!!,303446068,John,Manhattan,Upper East Side,40.76150,-73.96198,Private room,81,6,1,2020-07-29,1.00,1,365,True,False
45968,44353017,1 bedroom apartment in quiet location,10737943,David,Manhattan,Upper East Side,40.77196,-73.95178,Entire home/apt,62,30,0,NaN,NaN,7,350,True,False
46004,44378626,PRIVATE COZY STUDIO,107716952,Michael,Queens,Jamaica,40.69307,-73.80680,Entire home/apt,26,2,0,NaN,NaN,1,229,True,False
46011,44381182,Luxury Penthouse with the Best View in Brooklyn,1984312,Daniel,Brooklyn,Boerum Hill,40.68893,-73.98434,Entire home/apt,141,7,0,NaN,NaN,1,19,False,True
46043,44406609,Historic Townhouse w/ Private Landscaped Yard,6634085,Michael,Brooklyn,Bedford-Stuyvesant,40.68384,-73.95376,Entire home/apt,110,3,0,NaN,NaN,1,52,False,True
46098,44448566,Penthouse apt,38347589,Michael,Manhattan,Hell's Kitchen,40.76740,-73.99255,Entire home/apt,600,1,0,NaN,NaN,1,365,False,False
46144,44475210,Bright and Cozy Bedroom in Shared Apt,236572440,David,Manhattan,East Harlem,40.78683,-73.94309,Private room,55,30,0,NaN,NaN,14,365,True,False
46149,44475911,Charming Bedroom Bright and Cozy (Shared),236572440,David,Manhattan,East Harlem,40.78703,-73.94415,Private room,53,30,0,NaN,NaN,14,365,True,False
46151,44476020,Colorfull and Modern Bedroom (Shared),236572440,David,Manhattan,East Harlem,40.78704,-73.94425,Private room,49,30,0,NaN,NaN,14,365,True,False
46152,44476440,Best value double room in New York (Shared),236572440,David,Manhattan,East Harlem,40.78520,-73.94317,Private room,45,30,0,NaN,NaN,14,365,True,False
46154,44476634,Best value single room in New York (Shared),236572440,David,Manhattan,East Harlem,40.78481,-73.94372,Private room,45,30,0,NaN,NaN,14,350,True,False
46155,44476765,Red Superior double Bedroom (Shared),236572440,David,Manhattan,East Harlem,40.78479,-73.94312,Private room,45,30,0,NaN,NaN,14,365,True,False
46183,44491230,cozy two bedroom apartment near the beach,59215768,John,Queens,Rockaway Beach,40.58935,-73.80996,Entire home/apt,179,2,0,NaN,NaN,2,349,False,False
46229,44534901,Sunny Sanctuary Room + Prospect Park/Trains,11308947,Michael,Brooklyn,Prospect-Lefferts Gardens,40.65512,-73.96011,Private room,45,1,0,NaN,NaN,2,359,True,True
46270,44568305,Hope you feel home here,162021372,Michael,Manhattan,Washington Heights,40.85259,-73.93420,Private room,57,1,0,NaN,NaN,1,365,True,False
46326,44609991,"THE ""BUSHWICK EXPERIENCE""- CENTER OF IT ALL!!!",23296177,Daniel,Brooklyn,Bushwick,40.70326,-73.92547,Private room,80,1,0,NaN,NaN,1,90,True,True
46332,44615784,Feel at home in the heart of Williamsburg,40999075,John,Brooklyn,Greenpoint,40.71975,-73.95213,Entire home/apt,105,2,0,NaN,NaN,1,13,False,True
46350,44631955,Large 1 Bedroom on Upper West Side. Prime Loca...,17070752,David,Manhattan,Upper West Side,40.78744,-73.97571,Entire home/apt,125,7,0,NaN,NaN,1,350,False,False
46362,44639591,Central & Stylish 1 Bedroom Apt - Heart of Che...,286136716,John,Manhattan,Chelsea,40.74568,-73.99694,Entire home/apt,110,30,0,NaN,NaN,3,110,False,False
46396,44661297,Flushing Sunshine home #101,361579037,Daniel,Queens,Flushing,40.74603,-73.82837,Private room,52,1,0,NaN,NaN,2,360,True,False
46403,44662157,Flushing Sunshine home #102,361579037,Daniel,Queens,Flushing,40.74441,-73.82829,Private room,55,1,3,2020-08-16,3.00,2,365,True,False
46455,44697211,Davidâ€™s Queen Sized Room,343477029,David,Queens,Far Rockaway,40.59460,-73.75875,Private room,95,1,0,NaN,NaN,1,365,True,False
46508,44797527,Long-Term: Furnished Apt in Nolita w/ Amenities,19448640,David,Manhattan,Nolita,40.72289,-73.99400,Entire home/apt,140,30,0,NaN,NaN,1,282,False,False

In [7]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 


c1 = df['neighbourhood'] == 'Williamsburg'

df['adjusted_price'] = np.where(c1, df['price'] + 100, df['price'])
df[['neighbourhood', 'price', 'adjusted_price']]

                   neighbourhood  price  adjusted_price
0                        Midtown    175             175
1                   Clinton Hill     75              75
2             Bedford-Stuyvesant     60              60
3                    Sunset Park    175             175
4                 Hell's Kitchen     65              65
5                Upper West Side     75              75
6                      Chinatown    140             140
7                   West Village    160             160
8                    South Slope     88              88
9                Upper West Side     85              85
10                  West Village     65              65
11                  Williamsburg    109             209
12                   East Harlem    239             239
13                   Fort Greene    182             182
14                   East Harlem     96              96
15                  Williamsburg    299             399
16            Bedford-Stuyvesant    120             120
17               Windsor Terrace    135             135
18                        Inwood     86              86
19                  East Village    220             220
20                        Harlem     55              55
21            Bedford-Stuyvesant     70              70
22                   South Slope     88              88
23                      Flatbush    150             150
24               Lower East Side     40              40
25                  East Village     40              40
26                        Harlem    150             150
27     Prospect-Lefferts Gardens     95              95
28              Long Island City    130             130
29            Bedford-Stuyvesant    100             100
...                          ...    ...             ...
46497                   Rosedale     70              70
46498                  Wakefield    152             152
46499                     Harlem    250             250
46500                Murray Hill    381             381
46501                    Chelsea     62              62
46502                    Chelsea     62              62
46503                    Chelsea     62              62
46504                  Chinatown    124             124
46505                   Bushwick     96              96
46506            Upper West Side    400             400
46507               Vinegar Hill    201             201
46508                     Nolita    140             140
46509         Financial District   1806            1806
46510              Crown Heights     61              61
46511         Financial District   1806            1806
46512         Financial District    169             169
46513               Williamsburg    180             280
46514                  Rego Park     45              45
46515                     Nolita    175             175
46516         Financial District     60              60
46517               Williamsburg     55             155
46518              Crown Heights     61              61
46519               Clinton Hill    253             253
46520                 St. Albans     44              44
46521                    Chelsea    140             140
46522                   Gramercy    145             145
46523         Washington Heights     87              87
46524              East Flatbush     59              59
46525            Upper West Side     80              80
46526                  Gravesend     66              66

[46527 rows x 3 columns]

In [8]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  

df['room_type'].value_counts() / df['room_type'].value_counts().sum()                                                       

# same result
# df['room_type'].vaule_counts(normalize = True)

Entire home/apt    0.515787
Private room       0.454446
Shared room        0.021213
Hotel room         0.008554
Name: room_type, dtype: float64

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [9]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.
df.groupby('neighbourhood_group')['calculated_host_listings_count'].sum()

neighbourhood_group
Bronx              2619
Brooklyn          45790
Manhattan        180430
Queens            44534
Staten Island       692
Name: calculated_host_listings_count, dtype: int64

In [10]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 

df.groupby('neighbourhood_group')['price'].mean()

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [11]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


df.groupby('neighbourhood_group')['price'].agg(['min', 'max'])

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [12]:
# 4. Using `groupby`, find the mean price for each room type in each neighbourhood_group.

#df.groupby('room_type')['price'].mean()

# double group by
df.groupby(['neighbourhood_group','room_type'])['price'].mean();

room_type
Entire home/apt    199.395950
Hotel room         275.015075
Private room        91.453084
Shared room         87.063830
Name: price, dtype: float64

In [13]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.
gb_cols = ['neighbourhood_group', 'room_type']
df.groupby(gb_cols)['price'].agg(['count', 'min', 'max', 'mean', 'median', 'std'])

                                     count  min    max        mean  median  \
neighbourhood_group room_type
Bronx               Entire home/apt    415   25   1404  138.004819     103
                    Private room       722   16    700   68.419668      55
                    Shared room         46   20    800   66.391304      44
Brooklyn            Entire home/apt   9112   20  10000  171.587687     135
                    Hotel room          30    0    399  147.300000     129
                    Private room      9159   10   2500   71.291189      60
                    Shared room        331   15   1500   57.870091      36
Manhattan           Entire home/apt  12209    0  10000  231.335572     165
                    Hotel room         351    0   2211  292.515670     210
                    Private room      7601   10  10000  128.277069      80
                    Shared room        419   10  10000  111.735084      60
Queens              Entire home/apt   2090   10  10000  150.168900     115
                    Hotel room          17    0    249  139.058824     149
                    Private room      3499   18   9000   69.972564      55
                    Shared room        185   14   3000   89.891892      40
Staten Island       Entire home/apt    172   39   1200  151.720930     111
                    Private room       163   20    800   70.312883      55
                    Shared room          6   19     82   46.000000      38

                                            std
neighbourhood_group room_type
Bronx               Entire home/apt  126.032106
                    Private room      57.337866
                    Shared room      114.442703
Brooklyn            Entire home/apt  236.732843
                    Hotel room        91.153206
                    Private room      69.023165
                    Shared room       92.217618
Manhattan           Entire home/apt  410.306439
                    Hotel room       315.924085
                    Private room     448.677306
                    Shared room      502.728868
Queens              Entire home/apt  252.606739
                    Hotel room        50.743806
                    Private room     163.814468
                    Shared room      275.675158
Staten Island       Entire home/apt  147.518392
                    Private room      70.759593
                    Shared room       28.446441

# Join and file saving.
1. Load the `prices.csv` and the `n_listings.csv`


2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']
       
       
3. Save your joined csv as `joined.csv`


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [14]:
# 1. Load the `prices.csv` and the `n_listings.csv`

dfprices = pd.read_csv('data/prices.csv',sep = ',')
dfprices
dflistings = pd.read_csv('data/n_listings.csv', sep = ';')

In [15]:
# 2. Do join that keeps all the records for each table.

dfjoined = pd.merge(dfprices, dflistings, on='neighbourhood_group', how='outer')
dfjoined

  neighbourhood_group  mean_price  n_listings
0               Bronx   92.751479      1183.0
1            Brooklyn  120.225258     18632.0
2           Manhattan  191.880466     20580.0
3              Queens   99.754965         NaN
4       Staten Island  110.947214         NaN
5          LongIsland         NaN      4121.0

In [16]:
#3 Save your joined csv as joined.csv

save_as = 'joined.csv'
df.to_csv(save_as, index=False) 

#4 Load your saved table and see if it looks the same or different 
#that the DataFrame you used to create it.
dfoutcome = pd.read_csv('joined.csv')
dfoutcome

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,new_price,df_bk,adjusted_price
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365,False,False,175
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265,True,True,75
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365,True,True,60
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295,False,True,175
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340,True,False,65
5,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,75,2,118,2017-07-21,0.89,1,0,True,False,75
6,5238,Cute & Cozy Lower East Side 1 bdrm,7549,Ben,Manhattan,Chinatown,40.71344,-73.99037,Entire home/apt,140,1,161,2019-07-29,1.21,4,274,False,False,140
7,5552,Spacious river view in the West Village,8380,Maria,Manhattan,West Village,40.73552,-74.01042,Entire home/apt,160,3,66,2019-08-10,0.49,1,178,False,False,160
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344,True,True,88
9,6021,Wonderful Guest Bedroom in Manhattan CENTRAL PARK,11528,Claudio,Manhattan,Upper West Side,40.79826,-73.96113,Private room,85,2,123,2019-12-09,0.90,1,365,True,False,85
10,6090,West Village Nest - Superhost,11975,Alina,Manhattan,West Village,40.73530,-74.00525,Entire home/apt,65,30,29,2020-07-25,0.22,1,197,True,False,65
11,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,109,2,181,2020-03-16,1.32,1,0,False,True,209
12,6990,UES Beautiful Blue Room / 2 Bedrooms,16800,Cyn,Manhattan,East Harlem,40.78962,-73.94802,Entire home/apt,239,4,233,2019-12-09,1.77,1,365,False,False,239
13,7097,Perfect for Your Parents + Garden; Germ-Free,17571,Jane,Brooklyn,Fort Greene,40.69121,-73.97277,Entire home/apt,182,1,229,2020-07-20,1.78,2,325,False,True,182
14,7750,2 Furnished bedrooms next to Central Park,17985,Sing,Manhattan,East Harlem,40.79685,-73.94872,Private room,96,14,0,NaN,NaN,2,178,True,False,96
15,7801,Sweet and Spacious Brooklyn Loft,21207,Chaya,Brooklyn,Williamsburg,40.71842,-73.95718,Entire home/apt,299,3,9,2011-12-28,0.07,1,337,False,True,399
16,8490,"MAISON DES SIRENES1,bohemian apartment",25183,Nathalie,Brooklyn,Bedford-Stuyvesant,40.68371,-73.94028,Entire home/apt,120,2,115,2020-08-13,0.86,2,319,False,True,120
17,8505,Sunny Bedroom Across Prospect Park,25326,Gregory,Brooklyn,Windsor Terrace,40.65599,-73.97519,Private room,135,1,23,2019-10-14,0.84,2,89,False,True,135
18,8700,Magnifique Suite au N de Manhattan - vue Cloitres,26394,Claude & Sophie,Manhattan,Inwood,40.86754,-73.92639,Private room,86,4,0,NaN,NaN,1,0,True,False,86
19,9657,Modern 1 BR / NYC / EAST VILLAGE,21904,Dana,Manhattan,East Village,40.72920,-73.98542,Entire home/apt,220,3,33,2019-11-11,0.25,1,90,False,False,220
20,9704,Spacious 1 bedroom in luxe building,32045,Teri,Manhattan,Harlem,40.81305,-73.95466,Private room,55,2,98,2020-03-14,1.30,1,354,True,False,55
21,10452,Large B&B Style rooms,35935,Angela,Brooklyn,Bedford-Stuyvesant,40.68310,-73.95473,Private room,70,3,75,2019-10-12,0.60,2,365,True,True,70
22,10962,"Lovely Room 2; Garden; Best area, Legal",9744,Laurie,Brooklyn,South Slope,40.66869,-73.98780,Private room,88,4,180,2020-08-03,1.36,3,365,True,True,88
23,11943,Country space in the city,45445,Harriet,Brooklyn,Flatbush,40.63702,-73.96327,Private room,150,1,0,NaN,NaN,1,365,False,True,150
24,12048,LowerEastSide apt share shortterm 1,7549,Ben,Manhattan,Lower East Side,40.71401,-73.98917,Shared room,40,1,219,2019-11-13,1.67,4,226,True,False,40
25,12192,ENJOY Downtown NYC!,46978,Edward,Manhattan,East Village,40.72290,-73.98199,Private room,40,2,262,2020-03-17,1.99,2,46,True,False,40
26,12343,BEST BET IN HARLEM,47727,Earl,Manhattan,Harlem,40.81175,-73.94478,Entire home/apt,150,7,107,2019-12-07,0.83,1,364,False,False,150
27,12627,Entire apartment in central Brooklyn neighborh...,49670,Rana,Brooklyn,Prospect-Lefferts Gardens,40.65944,-73.96238,Entire home/apt,95,30,13,2019-12-05,0.36,1,156,True,True,95
28,12937,"1 Stop fr. Manhattan! Private Suite,Landmark B...",50124,Orestes,Queens,Long Island City,40.74771,-73.94740,Private room,130,2,280,2020-03-15,2.26,1,246,False,False,130
29,12940,Charming Brownstone 3 - Near PRATT,50148,Adreinne,Brooklyn,Bedford-Stuyvesant,40.68111,-73.95591,Entire home/apt,100,5,66,2020-03-02,0.51,1,19,False,True,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46497,44767959,A very quiet and crime free neighborhood,289154444,Olu,Queens,Rosedale,40.65192,-73.74515,Private room,70,1,0,NaN,NaN,2,139,True,False,70
46498,44768081,Home is where the heart is . Sharing mine with...,215027230,Caron,Bronx,Wakefield,40.88655,-73.86012,Private room,152,2,0,NaN,NaN,1,354,False,False,152
46499,44769471,Luxury 2 Bedroom 2 Bath Townhouse in Manhattan,1556814,Tammy,Manhattan,Harlem,40.81543,-73.94143,Entire home/apt,250,5,0,NaN,NaN,7,364,False,False,250
46500,44770013,Luxury Building. Panoramic Views!,17532419,Elena,Manhattan,Murray Hill,40.74541,-73.97361,Entire home/apt,381,4,0,NaN,NaN,1,360,False,False,381
46501,44789250,Private Room Chelsea 4A,241889662,Incentra Village Hotel,Manhattan,Chelsea,40.75049,-73.99528,Private room,62,1,0,NaN,NaN,36,364,True,False,62
46502,44789815,Private Room Chelsea 3D,241889662,Incentra Village Hotel,Manhattan,Chelsea,40.74834,-73.99656,Private room,62,1,0,NaN,NaN,36,362,True,False,62
46503,44790395,Private Room Chelsea 2D,241889662,Incentra Village Hotel,Manhattan,Chelsea,40.74922,-73.99714,Private room,62,1,0,NaN,NaN,36,365,True,False,62
46504,44791688,1 bdrm apt. on Orchard and Broome LES,8737911,Laura,Manhattan,Chinatown,40.71702,-73.99069,Entire home/apt,124,1,0,NaN,NaN,1,321,False,False,124
46505,44791984,very convenient area right next to JMZ train,86766592,Gabby,Brooklyn,Bushwick,40.69874,-73.93696,Private room,96,1,0,NaN,NaN,1,174,True,True,96
46506,44792997,The Best of the Upper Westside,362369539,Siobhan,Manhattan,Upper West Side,40.79261,-73.97671,Entire home/apt,400,4,0,NaN,NaN,1,4,False,False,400
46507,44795562,Spacious Brooklyn Home with Private Roofdeck,4035493,Jessica,Brooklyn,Vinegar Hill,40.70358,-73.98217,Private room,201,5,0,NaN,NaN,1,45,False,True,201
46508,44797527,Long-Term: Furnished Apt in Nolita w/ Amenities,19448640,David,Manhattan,Nolita,40.72289,-73.99400,Entire home/apt,140,30,0,NaN,NaN,1,282,False,False,140
46509,44798678,Sonder *Private 1BR Apartment* at Battery Park,219517861,Sonder (NYC),Manhattan,Financial District,40.70454,-74.01647,Entire home/apt,1806,2,0,NaN,NaN,43,337,False,False,1806
46510,44798876,Unique & beautiful design! Skylights-Washer/dryer,143513836,Elisabeth,Brooklyn,Crown Heights,40.67156,-73.91651,Private room,61,30,0,NaN,NaN,5,329,True,True,61
46511,44799007,Sonder at Battery Park | Studio with Weekly Di...,219517861,Sonder (NYC),Manhattan,Financial District,40.70439,-74.01470,Entire home/apt,1806,2,0,NaN,NaN,43,337,False,False,1806
46512,44799074,Sonder *Weekly Discounts* ADA Studio at Batter...,219517861,Sonder (NYC),Manhattan,Financial District,40.70469,-74.01473,Entire home/apt,169,2,0,NaN,NaN,43,337,False,False,169
46513,44800276,"Williamsburg 1 Bedroom, Spacious and Classy",361034257,Angelo + Amirah,Brooklyn,Williamsburg,40.71283,-73.95400,Entire home/apt,180,7,0,NaN,NaN,1,364,False,True,280
46514,44801333,Like a home,244745075,Tamar,Queens,Rego Park,40.71973,-73.86140,Private room,45,7,0,NaN,NaN,1,359,True,False,45
46515,44801335,Bright & Cozy Nolita 1 Bedroom,361814116,Lorena & Mario,Manhattan,Nolita,40.72035,-73.99436,Entire home/apt,175,7,0,NaN,NaN,1,364,False,False,175
46516,44801958,Luxury building apartment in FiDi Manhattan,82696573,Kendall,Manhattan,Financial District,40.70629,-74.00588,Private room,60,120,0,NaN,NaN,1,349,True,False,60
46517,44802032,A very large room in Williamsburg,213793805,Omer,Brooklyn,Williamsburg,40.71970,-73.95632,Private room,55,14,0,NaN,NaN,1,45,True,True,155
46518,44802224,Unique & beautiful design! Skylights-Washer/dryer,143513836,Elisabeth,Brooklyn,Crown Heights,40.67302,-73.91695,Private room,61,30,0,NaN,NaN,5,363,True,True,61
46519,44803201,1200 SF Duplex apt in an old shoe factory/ mon...,921746,Michael + JosuÃ©,Brooklyn,Clinton Hill,40.69034,-73.96179,Entire home/apt,253,30,0,NaN,NaN,1,74,False,True,253
46520,44804690,"Cozy place, peaceful, friendly and affordable.",362419479,Elia,Queens,St. Albans,40.69980,-73.77104,Private room,44,1,0,NaN,NaN,1,161,True,False,44
46521,44807338,Modern luxury Chelsea one bedroom,36370873,Ashley,Manhattan,Chelsea,40.74698,-73.99512,Entire home/apt,140,7,0,NaN,NaN,1,358,False,False,140
46522,44807522,Designer Gramercy Studio Townhouse by UNSQ,12941925,Brian,Manhattan,Gramercy,40.73433,-73.98383,Entire home/apt,145,7,0,NaN,NaN,1,164,False,False,145
46523,44807786,Cozy & comfy apt in the heart of Inwood Manhattan,284790520,Salar,Manhattan,Washington Heights,40.85820,-73.92733,Entire home/apt,87,6,0,NaN,NaN,2,85,True,False,87
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90,True,True,59
46525,44814944,Upper West Side studio 86th Street,4039777,Fernando,Manhattan,Upper West Side,40.78731,-73.97029,Entire home/apt,80,30,0,NaN,NaN,1,113,True,False,80
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50â€™ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38,True,True,66

# Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

In [17]:
df1 = pd.read_csv('data/grammys.csv')
df1

,year,category,nominee,workers,winner
0,1959,Album of the Year,The Music from Peter Gunn.,Henry Mancini,True
1,1959,Best Album Cover,Only the Lonely,Frank Sinatra (art director),True
2,1959,Best Arrangement,The Music From Peter Gunn,Henry Mancini (artist/arranger),True
3,1959,Best Classical Performance - Chamber Music (in...,Beethoven: Quartet 130,"The Hollywood String Quartet, Paul Shure (arti...",True
4,1959,Best Classical Performance - Instrumentalist (...,Segovia Golden Jubilee,AndrÃ©s Segovia,True
5,1959,Best Classical Performance - Instrumentalist (...,Segovia Golden Jubilee,AndrÃ©s Segovia (artist),True
6,1959,Best Classical Performance - Instrumentalist (...,Tchaikovsky: Piano Concerto No. 1 In B Flat Mi...,Van Cliburn (piano) (artist),True
7,1959,Best Classical Performance - Operatic or Choral,Virtuoso,Robert Wagner (choir director),True
8,1959,Best Classical Performance - Orchestra,Gaiete Parisienne,Felix Slatkin (conductor) (artist),True
9,1959,Best Classical Performance - Vocal Soloist (wi...,Operatic Recital,Renata Tebaldi (soprano) (artist),True
10,1959,Best Comedy Performance,The Chipmunk Song,Ross Bagdasarian (artist),True
11,1959,Best Country & Western Performance,Tom Dooley,The Kingston Trio (artist),True
12,1959,Best Country and Western Performance,Tom Dooley.,The Kingston Trio,True
13,1959,Best Engineered Record (Classical),Duets with a Spanish Guitar,"Laurindo Almeida, Salli Terri, Sherwood Hall III",True
14,1959,Best Engineered Record - Non-Classical,The Chipmunk Song,"Ross Bagdasarian (as David Seville), Ted Keep ...",True
15,1959,Best Instrumental Arrangement,The Music from Peter Gunn.,Henry Mancini,True
16,1959,Best Instrumental Composition,Cross Country Suite.,Nelson Riddle,True
17,1959,"Best Jazz Performance, Group",Basie.,Count Basie,True
18,1959,"Best Jazz Performance, Individual",Ella Fitzgerald Sings the Duke Ellington Songb...,Ella Fitzgerald,True
19,1959,Best Musical Composition First Recorded and Re...,Cross Country Suite,Nelson Riddle (artist/composer),True
20,1959,Best Original Cast Album (Broadway or TV),The Music Man,"Robert Preston, Barbara Cook, David Burns, Edd...",True
21,1959,Best Performance by a Dance Band,Basie,Count Basie (artist),True
22,1959,Best Performance by a Vocal Group or Chorus,That Old Black Magic,"Keely Smith, Louis Prima",True
23,1959,Best Performance by an Orchestra - for Other T...,Billy May's Big Fat Brass,Billy May,True
24,1959,"Best Performance, Documentary or Spoken Word",The Best Of The Stan Freberg Shows,Stan Freberg (narrator),True
25,1959,Best R&B Vocal Performance by a Duo or Group,Tequila,"The Champs, Gene Alden, Buddy Bruce, Dave Burg...",True
26,1959,Best Recording for Children,The Chipmunk Song (Christmas Don't Be Late),Ross Bagdasarian,True
27,1959,Best Rhythm & Blues Performance,Tequila,The Champs (artist),True
28,1959,"Best Sound Track Album, Dramatic Picture Score...",Gigi,AndrÃ© Previn (artist),True
29,1959,"Best Soundtrack Album, Dramatic Picture Score ...",Gigi,AndrÃ© Previn,True
...,...,...,...,...,...
6293,2019,Best Traditional R&B Performance,Bet Ain't Worth the Hand,Leon Bridges (artist),True
6294,2019,Best Traditional R&B Performance,Don't Fall Apart on Me Tonight,Bettye LaVette (artist),False
6295,2019,Best Traditional R&B Performance,Honest,Major. (artist),False
6296,2019,Best Tropical Latin Album,Anniversary,"Spanish Harlem Orchestra (artist), Doug Beaver...",True
6297,2019,Best Tropical Latin Album,Ponle Actitud,Felipe PelÃ¡ez (artist),False
6298,2019,Best Tropical Latin Album,Orquesta AkokÃ¡n,Orquesta AkokÃ¡n (artist),False
6299,2019,Best Urban Contemporary Album,Everything is Love,"The Carters (artist/producer), Gimel Keaton (e...",True
6300,2019,Best Urban Contemporary Album,Chris Dave and the Drumhedz,Chris Dave (artist),False
6301,2019,Best Urban Contemporary Album,War & Leisure,Miguel (artist),False
6302,2019,Best World Music Album,Freedom,"Soweto Gospel Choir (artist), Diniloxolo Ndlak...",True
6303,2019,Best World Music Album,Deran,Omara Bombino Moctar (artist),False
6304,2019,Best World Music Album,The Lost Songs of World War II,Yiddish Glory (artist),False
6305,2019,Lifetime Achievement Award,Billy Eckstine,NaN,True
6306,2019,Lifetime Achievement Award,Dionne Warwick,NaN,True
6307,2019,Lifetime Achievement Award,George Clinton and Parliament Funkadelic,NaN,True
6308,2019,Lifetime Achievement Award,Sam & Dave,NaN,True
6309,2019,"Producer of the Year, Classical",Blanton Alspaugh,NaN,True
6310,2019,"Producer of the Year, Classical",Dirk Sobotka (producer),NaN,False
6311,2019,"Producer of the Year, Classical",Judith Sherman (producer),NaN,False
6312,2019,"Producer of the Year, Non-Classical",Pharrell Williams,NaN,True
6313,2019,"Producer of the Year, Non-Classical",Kanye West (producer),NaN,False
6314,2019,"Producer of the Year, Non-Classical",Linda Perry (producer),NaN,False
6315,2019,Record of the Year,This is America,"Donald Glover (artist/producer), Ludwig GÃ¶rans...",True
6316,2019,Record of the Year,I Like It,"Cardi B (artist), Bad Bunny (artist), J Balvin...",False
6317,2019,Record of the Year,All the Stars,"Kendrick Lamar (artist), SZA (artist), Al Shux...",False
6318,2019,Record of the Year,Rockstar,"Post Malone (artist), 21 Savage (artist), Loui...",False
6319,2019,Song of the Year,This is America (Childish Gambino),"Ludwig GÃ¶ransson (songwriter), Young Thug (son...",True
6320,2019,Song of the Year,The Joke (Brandi Carlile),"Brandi Carlile (songwriter), Dave Cobb (songwr...",False
6321,2019,Song of the Year,Boo'd Up (Ella Mai),"Ella Mai (songwriter), Larrance Dopson (songwr...",False
6322,2019,Song of the Year,In My Blood (Shawn Mendes),"Shawn Mendes (songwriter), Teddy Geiger (songw...",False

In [18]:
#  1. Who was won Album of the Year in 2016?
condition1 = df1['year'] == 2016
condition2 = df1['winner'] == True
df1[condition1 & condition2]

,year,category,nominee,workers,winner
5505,2016,Album of the Year,1989.,"Taylor Swift (artist/producer), Jack Antonoff ...",True
5509,2016,Best Album Notes,"Love Has Many Faces: A Quartet, A Ballet, Wait...",Joni Mitchell (album notes writer),True
5510,2016,Best Alternative Music Album,Sound & Color.,Alabama Shakes,True
5513,2016,Best American Roots Performance,See That My Grave Is Kept Clean,Mavis Staples (artist),True
5514,2016,Best American Roots Song,24 Frames,Jason Isbell (songwriter),True
5515,2016,Best Americana Album,Something More Than Free,"Jason Isbell (artist), Dave Cobb (producer)",True
5516,2016,"Best Arrangement, Instrumental or a Cappella",Dance Of The Sugar Plum Fairy,"Pentatonix (arranger), Ben Bram (arranger)",True
5517,2016,"Best Arrangement, Instruments and Vocals",Sue (Or In A Season Of Crime),Maria Schneider (arranger),True
5518,2016,Best Bluegrass Album,The Muscle Shoals Recordings,The Steeldrivers (producer/artist),True
5519,2016,Best Blues Album,Born To Play Guitar,"Tom Hambridge (producer), Buddy Guy (artist)",True
5520,2016,Best Boxed or Special Limited Edition Package,"The Rise & Fall Of Paramount Records, Volume T...","Jack White (art director), Susan Archie (art d...",True
5521,2016,Best Chamber Music/Small Ensemble Performance,Filament,"Bryce Dessner (producer), Jonathan Low (engineer)",True
5522,2016,Best Children's Album,Home,"Dominic Fallacaro (producer), Tim Kubart (artist)",True
5523,2016,Best Choral Performance,Rachmaninoff: All-Night Vigil,"Kansas City Chorale (artist), Joseph Warner (a...",True
5524,2016,Best Classical Compendium,Paulus: Three Places Of Enlightenment; Veil Of...,"Giancarlo Guerrero (conductor/artist), Tim Han...",True
5525,2016,Best Classical Instrumental Solo,"Dutilleux: Violin Concerto, L'Arbre Des Songes","Seattle Symphony Orchestra, Ludovic Morlot (co...",True
5526,2016,Best Classical Solo Vocal Album,Joyce & Tony - Live From Wigmore Hall,"Jonathan Allen (engineer), Stephen Johns (prod...",True
5527,2016,Best Comedy Album,Live at Madison Square Garden.,Louis C.K.,True
5530,2016,Best Compilation Soundtrack for Visual Media,Season 1.,Glen Campbell: I'll Be Me,True
5533,2016,Best Contemporary Christian Music Album,This Is Not A Test,"Bryan Fowler (engineer/mixer), Toby McKeehan (...",True
5534,2016,Best Contemporary Christian Music Performance/...,Holy Spirit,Francesca Battistelli (artist),True
5535,2016,Best Contemporary Classical Composition,Paulus: Prayers & Remembrances,Stephen Paulus (composer),True
5536,2016,Best Contemporary Instrumental Album,Sylva.,"Snarky Puppy, Metropole Orkest",True
5539,2016,Best Country Album,Traveller,"Chris Stapleton (artist/producer), Dave Cobb (...",True
5540,2016,Best Country Duo/Group Performance,Girl Crush,Little Big Town (artist),True
5541,2016,Best Country Solo Performance,Traveller.,Chris Stapleton,True
5544,2016,Best Country Song,Girl Crush,"Little Big Town (artist), Liz Rose (songwriter...",True
5545,2016,Best Dance Recording,Where Are Ãœ Now.,"Skrillex (artist/producer/mixer), Diplo (artis...",True
5548,2016,Best Electronic/Dance Album,Skrillex and Diplo Present Jack Ãœ.,"Skrillex, Diplo",True
5551,2016,"Best Engineered Album, Classical",Ask Your Mama,"San Francisco Ballet Orchestra (artist), Georg...",True
...,...,...,...,...,...
5582,2016,Best Orchestral Performance,Shostakovich: Under Stalin's Shadow - Symphony...,"Andris Nelsons (conductor), Shawn Murphy (prod...",True
5583,2016,Best Pop Duo/Group Performance,Uptown Funk.,"Mark Ronson, Bruno Mars",True
5585,2016,Best Pop Solo Performance,Thinking Out Loud.,Ed Sheeran,True
5587,2016,Best Pop Vocal Album,1989.,Taylor Swift,True
5590,2016,Best R&B Album,Black Messiah.,"D'Angelo, The Vanguard",True
5593,2016,Best R&B Song,Really Love.,"D'Angelo (songwriter), Gina Figueroa (songwrit...",True
5596,2016,Best Rap Album,To Pimp a Butterfly.,Kendrick Lamar,True
5599,2016,Best Rap Performance,Alright.,Kendrick Lamar,True
5602,2016,Best Rap Song,Alright.,"Kendrick Lamar (songwriter), Kawan Prather (so...",True
5605,2016,Best Rap/Sung Collaboration,These Walls.,"Kendrick Lamar, Bilal (featured artist), Anna ...",True
5608,2016,Best Recording Package,Still The King: Celebrating The Music Of Bob W...,"Sarah Dodds (art director), Shauna Dodds (art ...",True
5609,2016,Best Reggae Album,Strictly Roots,Morgan Heritage (producer),True
5610,2016,Best Regional Mexican Music Album (including t...,Realidades - Deluxe Edition,Los Tigres del Norte (producer/artist),True
5611,2016,Best Remixed Recording,Uptown Funk (Dave AudÃ© Remix),"Dave AudÃ© (remixer), Mark Ronson (artist), Bru...",True
5612,2016,Best Rock Album,Drones.,Muse,True
5615,2016,Best Rock Performance,Don't Wanna Fight.,Alabama Shakes,True
5618,2016,Best Rock Song,Don't Wanna Fight.,Alabama Shakes (songwriters),True
5621,2016,Best Roots Gospel Album,Still Rockin' My Soul,"Brandon Perdue (engineer/mixer), Lee Olsen (pr...",True
5622,2016,Best Score Soundtrack for Visual Media,Birdman or (The Unexpected Virtue of Ignorance),Antonio Sanchez,True
5625,2016,Best Song Written for Visual Media,Glory.,Selma,True
5628,2016,"Best Spoken Word Album (includes poetry, audio...",A Full Life: Reflections at Ninety,"Jimmy Carter (artist), Elisa Shokoff (producer)",True
5629,2016,Best Surround Sound Album,Amused To Death,"Roger Waters (artist), James Guthrie (surround...",True
5630,2016,Best Traditional R&B Performance,Little Ghetto Boy.,Lalah Hathaway,True
5633,2016,Best Tropical Latin Album,Son De PanamÃ¡,"Ignacio Molina (engineer), Pablo Governatori (...",True
5634,2016,Best Urban Contemporary Album,Beauty Behind the Madness.,The Weeknd,True
5637,2016,Best World Music Album,Sings,"AngÃ©lique Kidjo (artist/producer), Jean Hebrai...",True
5638,2016,"Producer of the Year, Classical",Judith Sherman (producer),NaN,True
5639,2016,"Producer of the Year, Non-Classical",Jeff Bhasker (producer),NaN,True
5640,2016,Record of the Year,Uptown Funk.,"Mark Ronson (artist/producer/engineer/mixer), ...",True
5643,2016,Song of the Year,Thinking Out Loud.,"Ed Sheeran (artist/songwriter), Amy Wadge (art...",True

In [19]:
# 2. Who won Best Rap Album in 2009?
condition1 = df1['year'] == 2009
condition2 = df1['category'] == 'Best Rap Album'
condition3 = df1['winner'] == True
df1[condition1 & condition2 & condition3]

      year        category         nominee     workers  winner
4396  2009  Best Rap Album  Tha Carter III  Lil' Wayne    True

In [20]:
# 3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

condition1 = df1['workers'] == 'Kendrick Lamar'

df1['get_nomiated'] = np.where(condition1, 1, 0)
#count the times when condition1 is true to get how many times KL is nomiated,
print(df1['get_nomiated'].value_counts())

condition2 = df1['winner'] == True
df1['win'] = np.where(condition1&condition2, 1, 0)
df1['win'].value_counts()

0    6317
1       6
Name: get_nomiated, dtype: int64

0    6319
1       4
Name: win, dtype: int64